name: Run Go Script on Master

on:
  push:
    branches:
      - master

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21

    - name: Grab Env
      env:
        FOO_BAR: ${{ secrets.FOO_BAR }}

    - name: Run Go Script
      run: |
        go run scripts/main.go  # Replace with the actual name of your Go script
